import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '@/widgets/Header/Header'

import { ReactNode } from 'react'
import 'react-modern-drawer/dist/index.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: ReactNode
}

export default function RootLayout(props: Props) {
  return (
    <html className="bg-accent-dark" lang="en">
      <body className={inter.className}>
        <Header />

        {props.children}
      </body>
    </html>
  )
}
